global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['fastapi:9000']  

  - job_name: 'torchserve'
    static_configs:
      - targets: ['model-server:8082']
