apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: ${DOCKER_USERNAME}/fastapi:latest
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /app
              name: fastapi-code
          env:
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: groq-api-key
                  key: GROQ_API_KEY

      volumes:
      - name: fastapi-code
        hostPath:
          path: /mnt/data/fastapi-code  # Replace with appropriate mount
          type: DirectoryOrCreate

      
