apiVersion: v1
kind: Service
metadata:
  name: torchserve
spec:
  type: LoadBalancer
  selector:
    app: torchserve
  ports:
  - port: 8080
    targetPort: 8080
  - port: 8081
    targetPort: 8081
  - port: 8082
    targetPort: 8082