apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd-retain
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer