name: Model-Server deployment to GCP - GKE 

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/model/**'
      - '.github/**'

jobs:
  deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure kubectl
        run: |
            gcloud container clusters get-credentials smart-agri-app-cluster \
            --zone asia-south1-a \
            --project ${{ secrets.GCP_PROJECT }}


      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/model-server:latest ./Backend/model
            docker push ${{ secrets.DOCKER_USERNAME }}/model-server:latest

      - name: Render deployment.yaml
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          envsubst < k8s/model-server/deployment.yaml > k8s/model-server/model-server-deployment.yaml

      - name: Installing KEDA
        run: kubectl apply -f https://github.com/kedacore/keda/releases/download/v2.10.1/keda-2.10.1.yaml

      - name: Wait for KEDA
        run: |
          kubectl wait deployment keda-operator --for=condition=Available=True --timeout=240s -n keda

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/model-server/model-server-deployment.yaml
          kubectl apply -f k8s/model-server/service.yaml
          kubectl apply -f k8s/model-server/model-store-pvc.yaml
          kubectl apply -f k8s/model-server/keda-model-server-scaledObject.yaml

        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
