name: React App deployment to GKE 

on:
  push:
    branches: [ main ]
    paths:
      - 'smart-agriculture-app/**'

jobs:
  deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Configure kubectl
        run: |
            gcloud container clusters get-credentials smart-agri-app-cluster \
            --zone asia-south1-a \
            --project ${{ secrets.GCP_PROJECT }}


      - name: Install GKE Auth Plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin --quiet

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/react:latest ./smart-agriculture-app
            docker push ${{ secrets.DOCKER_USERNAME }}/react:latest

      - name: Render deployment.yaml
        run: |
          export DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          envsubst < k8s/react/deployment.yaml > k8s/react/react-deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/react/react-deployment.yaml
          kubectl apply -f k8s/react/service.yaml

        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
